
import React, { useState } from 'react';
import { TABLE_NAME } from '../constants';

export const SqlHelper: React.FC = () => {
  const [copied, setCopied] = useState(false);

  const sqlCode = `create table ${TABLE_NAME} (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  acc_name text not null,
  amount numeric,
  acc_num text,
  bsb text,
  payid text,
  label text
);`;

  const handleCopy = () => {
    navigator.clipboard.writeText(sqlCode);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="mt-8 bg-slate-900 rounded-lg overflow-hidden shadow-xl border border-slate-700">
      <div className="px-4 py-3 bg-slate-800 flex justify-between items-center border-b border-slate-700">
        <h3 className="text-sm font-medium text-slate-200">Database Setup (Run in Supabase SQL Editor)</h3>
        <button
          onClick={handleCopy}
          className="text-xs font-semibold text-emerald-400 hover:text-emerald-300 transition-colors uppercase tracking-wider"
        >
          {copied ? 'Copied!' : 'Copy SQL'}
        </button>
      </div>
      <div className="p-4 overflow-x-auto">
        <pre className="text-xs sm:text-sm text-slate-300 font-mono leading-relaxed">
          <code>{sqlCode}</code>
        </pre>
      </div>
    </div>
  );
};